/** Curated CRD seeds preloaded on bare /chart for map testing. */
export type ChartSeedType = 'firm' | 'individual';
export type ChartSeedNode = { crd: string; type: ChartSeedType; label: string };
export const CHART_PRELOAD_SEEDS: ChartSeedNode[] = [
	{ crd: '159712', type: 'firm', label: 'CABOT LODGE SECURITIES LLC' },
	{ crd: '29299', type: 'firm', label: 'ITG INC.' },
	{ crd: '4890684', type: 'individual', label: 'Janice Celeste Sorial' },
	{ crd: '1015261', type: 'individual', label: 'Robert Jay Eide' },
	{ crd: '2322410', type: 'individual', label: 'Jeffrey Alan Churba' },
	{ crd: '4525887', type: 'individual', label: 'Edward Owen Mcconnell' },
	{ crd: '5824640', type: 'individual', label: 'Brenton Thai' },
	{ crd: '5917234', type: 'individual', label: 'Tatiana Cristina Parave Eckel' },
	{ crd: '2723431', type: 'individual', label: 'Bryan Scott Cram' },
	{ crd: '1042045', type: 'individual', label: 'Andrew John Okeefe' },
	{ crd: '6786408', type: 'individual', label: 'Annabella Campbell Rockwell' },
	{ crd: '2193978', type: 'individual', label: 'Antonio Dallaris' },
	{ crd: '4085618', type: 'individual', label: 'Francoise Loan Dix' },
	{ crd: '7991501', type: 'individual', label: 'Sean Easton' },
	{ crd: '5300554', type: 'individual', label: 'Heather Jill Nagengast' },
	{ crd: '3090032', type: 'individual', label: 'Timothy James Henderson' },
	{ crd: '7132964', type: 'individual', label: 'Raymond Kyle Lovelace' },
	{ crd: '1865319', type: 'individual', label: 'Shane T Triplett' },
	{ crd: '1479551', type: 'individual', label: 'Charles Evan Howell' },
	{ crd: '7346869', type: 'individual', label: 'Matthew J Lovelace' },
	{ crd: '1395210', type: 'individual', label: 'Paige Wyman Pierce' },
	{ crd: '5278886', type: 'individual', label: 'Steven M Draczynski' },
	{ crd: '8152117', type: 'individual', label: 'Owen J. Heaney' },
	{ crd: '2270130', type: 'individual', label: 'Jon Hunt' },
	{ crd: '2665535', type: 'individual', label: 'SCOTT MCADAM' },
	{ crd: '2169049', type: 'individual', label: 'Gregory J Remmes' },
	{ crd: '6546392', type: 'individual', label: 'Noah Butler Rhodes' },
	{ crd: '8061267', type: 'individual', label: 'Alexander David Israel' },
	{ crd: '7345383', type: 'individual', label: 'Kyle Dallen Baugh' },
	{ crd: '133798', type: 'firm', label: 'OCEANUS SECURITIES, LLC' },
	{ crd: '1349154', type: 'individual', label: 'Robert Nmn Campbell' },
	{ crd: '2856846', type: 'individual', label: 'Harrison S. Karp' },
	{ crd: '2552690', type: 'individual', label: 'MICHAEL ROBERT BOCINA' },
	{ crd: '6290239', type: 'individual', label: 'John Israel' },
	{ crd: '4991846', type: 'individual', label: 'Cindy Jane Lovelace' },
	{ crd: '6938578', type: 'individual', label: 'Ocean Strayhand' },
	{ crd: '1650853', type: 'individual', label: 'Steve Nmn Solano' },
	{ crd: '4240468', type: 'individual', label: 'Michael David Trump' },
	{ crd: '7954528', type: 'individual', label: 'Quintus Trufelli Smith' },
	{ crd: '6641808', type: 'individual', label: 'Zachary Israel' },
	{ crd: '5800871', type: 'individual', label: 'Jabulani Lovelace' },
	{ crd: '7927', type: 'firm', label: 'NORTHERN TRUST SECURITIES, INC.' },
	{ crd: '4259206', type: 'individual', label: 'Ryan Leslie Lachmansingh' },
	{ crd: '4275481', type: 'individual', label: 'Tracy Zimmerer' },
	{ crd: '501891', type: 'individual', label: 'Richard Lee Lovelace' },
	{ crd: '108928', type: 'firm', label: 'BLACKROCK INVESTMENT MANAGEMENT, LLC' },
	{ crd: '38642', type: 'firm', label: 'BLACKROCK INVESTMENTS, LLC' },
	{ crd: '2525', type: 'firm', label: 'DEUTSCHE BANK SECURITIES INC.' },
	{ crd: '6627', type: 'firm', label: 'EQUICO SECURITIES, INC.' },
	{ crd: '6363', type: 'firm', label: 'AMERICAN EXPRESS FINANCIAL ADVISORS INC.' },
	{ crd: '39670', type: 'firm', label: 'RESEARCH CAPITAL USA INC.' },
	{ crd: '107622', type: 'firm', label: 'METLIFE INVESTORS DISTRIBUTION COMPANY' },
	{ crd: '5657', type: 'firm', label: 'EMPIRE STATE FINANCIAL, INC.' },
	{ crd: '7691', type: 'firm', label: 'MERRILL LYNCH, PIERCE, FENNER & SMITH INCORPORATED' },
	{ crd: '5685', type: 'firm', label: 'PRUCO SECURITIES CORPORATION' },
	{ crd: '20472', type: 'firm', label: 'TIAA-CREF INDIVIDUAL & INSTITUTIONAL SERVICES, LLC' },
	{ crd: '4031', type: 'firm', label: 'HORNOR, TOWNSEND & KENT, INC.' },
	{ crd: '1272052', type: 'individual', label: 'STEPHANIE DALLAS' },
	{ crd: '5884184', type: 'individual', label: 'Robert Stokes Wise' },
	{ crd: '2210722', type: 'individual', label: 'JOHN GREGORY MARTINEZ' },
	{ crd: '8026346', type: 'individual', label: 'Logan Tex Ford' },
	{ crd: '1389294', type: 'individual', label: 'Kevin Patrick Dodds' },
	{ crd: '7616382', type: 'individual', label: 'Sara Rathbone Mooney' },
	{ crd: '1865081', type: 'individual', label: 'JOHN RAY WILLIAMS' },
	{ crd: '1032639', type: 'individual', label: 'Albert Quentin Murray III' },
	{ crd: '6572840', type: 'individual', label: 'Dimitri Dilhan Rodrigo' },
	{ crd: '2659721', type: 'individual', label: 'Townsend U Weekes' },
	{ crd: '5943888', type: 'individual', label: 'Spencer Owen Morse' },
	{ crd: '7208160', type: 'individual', label: 'Garrett M Facer' },
	{ crd: '2717305', type: 'individual', label: 'Jacqueline Lee Sloan Nowak' },
	{ crd: '4814964', type: 'individual', label: 'Patricia L Cerny' },
	{ crd: '8057689', type: 'individual', label: 'Jonathon Owen Gruber' },
	{ crd: '2177412', type: 'individual', label: 'MARK HUGO' },
	{ crd: '5971850', type: 'individual', label: 'OLEG CHANYSHEV' },
	{ crd: '4077413', type: 'individual', label: 'Matthew Mark Reynolds' },
	{ crd: '3139370', type: 'individual', label: 'Jeffrey Philip Heller' },
	{ crd: '4056573', type: 'individual', label: 'David Franklin Baugh' },
	{ crd: '5332253', type: 'individual', label: 'Denise Parejko Skweres' },
	{ crd: '7049272', type: 'individual', label: 'Zohaib Raza' },
	{ crd: '5939783', type: 'individual', label: 'David Harmon Haufe' },
	{ crd: '5941677', type: 'individual', label: 'Erik Theodore Swanson' },
	{ crd: '1163546', type: 'individual', label: 'MARIETTA MACKEVICH HESDORFFER' },
	{ crd: '2516596', type: 'individual', label: 'Nicole C Stokes' },
	{ crd: '5688427', type: 'individual', label: 'Brian Minto' },
	{ crd: '6711251', type: 'individual', label: 'Ashley Elizabeth Rodabaugh' },
	{ crd: '7848309', type: 'individual', label: 'Mason Bond Heflin' },
	{ crd: '1433823', type: 'individual', label: 'Jeffrey Lynn Bryan' },
	{ crd: '6181071', type: 'individual', label: 'Joshua Israel Berdet' },
	{ crd: '4642034', type: 'individual', label: 'Payal Gupta' },
	{ crd: '3251690', type: 'individual', label: 'Talib I Takruri' },
	{ crd: '5612359', type: 'individual', label: 'Will Geza Tuhacek' },
	{ crd: '2629833', type: 'individual', label: 'Wayne Alan Wurtsbaugh' },
	{ crd: '7226449', type: 'individual', label: 'Sean Michael Facey' },
	{ crd: '6661910', type: 'individual', label: 'Laura LaSalle' },
	{ crd: '6725614', type: 'individual', label: 'Abraham Daniel Israeli' },
	{ crd: '7482566', type: 'individual', label: 'Narendra Davangere-Venkatesh' },
	{ crd: '6549300', type: 'individual', label: 'Jonathan Wade Groom' },
	{ crd: '5997727', type: 'individual', label: 'Brian James Fay' },
	{ crd: '5525411', type: 'individual', label: 'BRENDAN ALEXANDER FISCHER' },
	{ crd: '1555979', type: 'individual', label: 'Debasish ("nmn") Banerjee' },
	{ crd: '5054581', type: 'individual', label: 'Lori Jeannette Shjarback Longenbach' },
	{ crd: '2453096', type: 'individual', label: 'Richard Ernest Onesto' },
	{ crd: '13041', type: 'firm', label: 'NATIONAL FINANCIAL SERVICES LLC' },
	{ crd: '3186352', type: 'individual', label: 'Janet Dyer' },
	{ crd: '5231387', type: 'individual', label: 'Jeremiah Joseph Runion' },
	{ crd: '283942', type: 'firm', label: 'Inc. Bofa Securities' },
	{ crd: '4418945', type: 'individual', label: 'Stephen Neal Karp' },
	{ crd: '21570', type: 'firm', label: 'AMERICAN SKANDIA MARKETING, INC.' },
	{ crd: '2639873', type: 'individual', label: 'PHIL T HARRIS' },
	{ crd: '5657792', type: 'individual', label: 'Peter Eugean Owen' },
	{ crd: '3487', type: 'firm', label: 'STATE FARM INVESTMENT MANAGEMENT CORP.' },
	{ crd: '149823', type: 'firm', label: 'VIRTU AMERICAS LLC' },
	{ crd: '41067', type: 'firm', label: 'DMK ADVISOR GROUP, INC.' },
	{ crd: '8122016', type: 'individual', label: 'Frederick William Drago' },
	{ crd: '1631198', type: 'individual', label: 'Douglas Macarthur Millar' },
	{ crd: '5094723', type: 'individual', label: 'Lony Floyd Parker' },
	{ crd: '5954564', type: 'individual', label: 'Jameela Lovelace' },
	{ crd: '1039556', type: 'individual', label: 'GARY LEO OLSON' },
	{ crd: '2159909', type: 'individual', label: 'Mary Bea Wilkinson' },
	{ crd: '1845071', type: 'individual', label: 'Jeffery Carl McKay' },
	{ crd: '4458909', type: 'individual', label: 'Shane Thomas Mcgrath' },
	{ crd: '6949587', type: 'individual', label: 'Susan F Axelrod' },
	{ crd: '1572778', type: 'individual', label: 'Kimberley Holweger' },
	{ crd: '4866129', type: 'individual', label: 'Michael James Molnar' },
	{ crd: '4709900', type: 'individual', label: 'Jeffrey Robert Buchheister' },
	{ crd: '4710068', type: 'individual', label: 'Daniel Paul Burkott' },
	{ crd: '106629', type: 'firm', label: 'PUTNAM INVESTMENT MANAGEMENT, LLC' },
	{ crd: '2796476', type: 'individual', label: 'Erik Bradley Niland' },
	{ crd: '2573549', type: 'individual', label: 'RICHARD THOMAS FOX' },
	{ crd: '2954103', type: 'individual', label: 'Summer Seltzer Arnold' },
	{ crd: '4302538', type: 'individual', label: 'Gerald Patterson' },
	{ crd: '5769181', type: 'individual', label: 'Maura Mizuguchi' },
	{ crd: '1921834', type: 'individual', label: 'Thomas William Halloran' },
	{ crd: '1346950', type: 'individual', label: 'TERESA ROSE WELLINGTON' },
	{ crd: '3083418', type: 'individual', label: 'Jonathan Trump' },
	{ crd: '1243224', type: 'individual', label: 'James Dale Price' },
	{ crd: '2272183', type: 'individual', label: 'Timothy Earl Mccoy Stinson' },
	{ crd: '5180100', type: 'individual', label: 'Kevin Lucius Mccreless' },
	{ crd: '7082559', type: 'individual', label: 'Steven Kenneth Bachmann' },
	{ crd: '1806953', type: 'individual', label: 'Daniel Adam Umansky' },
	{ crd: '6389152', type: 'individual', label: 'Valentina Veronica Tubac' },
	{ crd: '3178848', type: 'individual', label: 'Steven Thomas Malfitano' },
	{ crd: '1406115', type: 'individual', label: 'Craig M Long' },
	{ crd: '2627931', type: 'individual', label: 'Matthew Adam Schlueter' },
	{ crd: '4749171', type: 'individual', label: 'SAMUTH SIDEN EAN' },
	{ crd: '3215005', type: 'individual', label: 'Jonathan Wilbor Briggs' },
	{ crd: '6896737', type: 'individual', label: 'Samuel Eaton Terminello' },
	{ crd: '2655124', type: 'individual', label: 'Peter Francis Flynn' },
	{ crd: '3037902', type: 'individual', label: 'Patrick William Mckeon' },
	{ crd: '7659144', type: 'individual', label: 'PRIYANKA DHINGRA' },
	{ crd: '1545513', type: 'individual', label: 'Laura May Crosby-Brown' },
	{ crd: '5041587', type: 'individual', label: 'Jeromy D Wood' },
	{ crd: '2156290', type: 'individual', label: 'Sean Patrick Casey' },
	{ crd: '3141681', type: 'individual', label: 'GABRIELLA Jolan ANDRAS' },
	{ crd: '7907627', type: 'individual', label: 'Chengxi Gang' },
	{ crd: '7750551', type: 'individual', label: 'Jeremy Chong' },
	{ crd: '2065062', type: 'individual', label: 'MONICA LYN LITTLEFIELD' },
	{ crd: '2622761', type: 'individual', label: 'ANTONIO AVELINO GARCIA' },
	{ crd: '5059738', type: 'individual', label: 'Lisa Anne Gok' },
	{ crd: '7996345', type: 'individual', label: 'Serge Budevich' },
	{ crd: '7376607', type: 'individual', label: 'Rodney Cammeron Dowell' },
	{ crd: '2193426', type: 'individual', label: 'Thomas Byron Taylor' },
	{ crd: '1866723', type: 'individual', label: 'S RANDALL PAVLATOS' },
	{ crd: '3070202', type: 'individual', label: 'Elayne Camille Banks' },
	{ crd: '2390418', type: 'individual', label: 'SCOT PATRICK SAGESER' },
	{ crd: '2414139', type: 'individual', label: 'JAN WILLIAM ROGERS' },
	{ crd: '4807911', type: 'individual', label: 'Elisa Anne-Marie Del Valle' },
	{ crd: '3004604', type: 'individual', label: 'Stanley Robert Smiley' },
	{ crd: '3259012', type: 'individual', label: 'Dori Jamille Hammond' },
	{ crd: '2420144', type: 'individual', label: 'Christopher Mills Mitchell' },
	{ crd: '3132991', type: 'individual', label: 'Gregory Allen Cornick' },
	{ crd: '1377978', type: 'individual', label: 'JAMES EDWARD EASTON' },
	{ crd: '4780880', type: 'individual', label: 'Andrew David Watts' },
	{ crd: '1974671', type: 'individual', label: 'RICHARD JEFFERY ANTHONY' },
	{ crd: '2160203', type: 'individual', label: 'Raymond Ramos' },
	{ crd: '1965155', type: 'individual', label: 'Leann Renee Rummel' },
	{ crd: '1218879', type: 'individual', label: 'ROBERT EUGENE BERG' },
	{ crd: '1048237', type: 'individual', label: 'CHANG SOO HAN' },
	{ crd: '2670436', type: 'individual', label: 'John W Tsigakos' },
	{ crd: '3237500', type: 'individual', label: 'Shaneek Jovon Harness' },
	{ crd: '1961258', type: 'individual', label: 'CHRISTOPHER JON REINHOLZ' },
	{ crd: '2605497', type: 'individual', label: 'Robert Karl Baugh' },
	{ crd: '4697734', type: 'individual', label: 'KRISTIN GANG' },
	{ crd: '4330405', type: 'individual', label: 'TODD EDMONDSON' },
	{ crd: '3118554', type: 'individual', label: 'ANEIDRE LASHAWN AMERSON-ALLMAN' },
	{ crd: '2993505', type: 'individual', label: 'Joseph Daniel Neary' },
	{ crd: '7042846', type: 'individual', label: 'David James Van Havermaat' },
	{ crd: '4436212', type: 'individual', label: 'KENNETH MAX SHARROCK' },
	{ crd: '1497190', type: 'individual', label: 'Thomas J Sboto' },
	{ crd: '6766944', type: 'individual', label: 'Christian Winfield Mitchell' },
	{ crd: '4024999', type: 'individual', label: 'Richard Charles Vogel' },
	{ crd: '18464', type: 'firm', label: 'FORESTERS EQUITY SERVICES, INC.' },
	{ crd: '2799860', type: 'individual', label: 'Todd Christopher Mackay' },
	{ crd: '2572129', type: 'individual', label: 'Miles Michael Logothetis' },
	{ crd: '2430593', type: 'individual', label: 'Howell Booth Holland' },
	{ crd: '1632092', type: 'individual', label: 'RICHARD VAUGHAN DUNSTAN' },
	{ crd: '6581570', type: 'individual', label: 'Samuel John Adams' },
	{ crd: '1747251', type: 'individual', label: 'LEONARD VAUGHN DAYTON' },
	{ crd: '4587843', type: 'individual', label: 'KELLEY RENEE COLLINGWOOD' },
	{ crd: '1716104', type: 'firm', label: 'SUSAN MARY CYBERSKI' },
	{ crd: '2738091', type: 'individual', label: 'CHIKAKO KASHINO' },
	{ crd: '5133646', type: 'individual', label: 'KRISTIN VESIA PRENTICE' },
	{ crd: '3127973', type: 'individual', label: 'JONATHAN TJ ALTHOFF' },
	{ crd: '1108580', type: 'individual', label: 'MICHAEL LOUIS THIEL' },
	{ crd: '708042', type: 'individual', label: 'Howard Spindel' },
	{ crd: '2499960', type: 'individual', label: 'TIMOTHY DAVID TANNER' },
	{ crd: '2687068', type: 'individual', label: 'ROBERT GARLAND EDMONDSON' },
	{ crd: '1217606', type: 'individual', label: 'ADAM MICHAEL ISRAEL' },
	{ crd: '2914522', type: 'individual', label: 'Jerald Paul Facey' },
	{ crd: '7422638', type: 'individual', label: 'Abigail Elizabeth Miles' },
	{ crd: '6117461', type: 'individual', label: 'Miles H Longenbaugh' },
	{ crd: '8252140', type: 'individual', label: 'Benjamin B Israelsen' },
	{ crd: '2363949', type: 'individual', label: 'ROBERT ANTHONY GRANIERI' },
	{ crd: '6361574', type: 'individual', label: 'Nicholas Michael Leighton' },
	{ crd: '1022191', type: 'individual', label: 'ROBERT EUGENE FLETCHER' },
	{ crd: '2621445', type: 'individual', label: 'Andrew Michael Baugh' },
	{ crd: '5915862', type: 'individual', label: 'Allison Alexandra Bishop' },
	{ crd: '4032646', type: 'individual', label: 'Susan June Butrymowicz' },
	{ crd: '1018286', type: 'individual', label: 'David Brian Paige' },
	{ crd: '7066940', type: 'individual', label: 'Amit Agarwal' },
	{ crd: '4994948', type: 'individual', label: 'Nicholas Burritt Lane' },
	{ crd: '1312459', type: 'individual', label: 'Roger Pacheco' },
	{ crd: '1143896', type: 'individual', label: 'GARY JOE HOOTEN' },
	{ crd: '7055121', type: 'individual', label: 'Jing G Kessler' },
	{ crd: '2693303', type: 'individual', label: 'Jason Patrick Kavanaugh' },
	{ crd: '2312324', type: 'individual', label: 'MELISSA COCO OCEAN' },
	{ crd: '5829700', type: 'individual', label: 'Shannon Keith Clark' },
	{ crd: '107342', type: 'firm', label: 'FISHER INVESTMENTS' },
	{ crd: '4490863', type: 'individual', label: 'Amy Renee Longenbaugh' },
	{ crd: '5012022', type: 'individual', label: 'Gregory Dain Baugh' },
	{ crd: '3259826', type: 'individual', label: 'Kenneth Eugene Shade' },
	{ crd: '6037365', type: 'individual', label: 'Nicholas Adam Jendusa' },
	{ crd: '6768183', type: 'individual', label: 'Dathan Rayfield Stukes' },
	{ crd: '5123284', type: 'individual', label: 'Charity Lea Facemire' },
	{ crd: '1455056', type: 'individual', label: 'Arlington Syrie' },
	{ crd: '7540069', type: 'individual', label: 'Justus Lemon' },
	{ crd: '2182135', type: 'individual', label: 'Angelica A Magno' },
	{ crd: '1555436', type: 'individual', label: 'DAVID W NUELLE' },
	{ crd: '6996240', type: 'individual', label: 'Mano Dracolakis' },
	{ crd: '6131741', type: 'individual', label: 'Milena Esther Verdooren' },
	{ crd: '2912309', type: 'individual', label: 'Stephen Rocco Facella' },
	{ crd: '8089244', type: 'individual', label: 'Straton Facer' },
	{ crd: '7501947', type: 'individual', label: 'Langston Facen' },
	{ crd: '2341814', type: 'individual', label: 'James Arthur III Facey' },
	{ crd: '6652405', type: 'individual', label: 'Derick Enrique Facey' },
	{ crd: '5337868', type: 'individual', label: 'David A Facey' },
	{ crd: '5458604', type: 'individual', label: 'Cary Cy Warren Facer' },
	{ crd: '4749127', type: 'individual', label: 'Brent David Facemire' },
	{ crd: '1917050', type: 'individual', label: 'Andrew Ray Face' },
	{ crd: '7264641', type: 'individual', label: 'Forrest Dillon Longenbaugh' },
	{ crd: '6321', type: 'firm', label: 'IDS LIFE INSURANCE COMPANY' },
	{ crd: '7002808', type: 'individual', label: 'Eileen Bejasa' },
	{ crd: '17868', type: 'firm', label: 'U.S. BANCORP INVESTMENTS, INC.' },
	{ crd: '14455', type: 'firm', label: 'U.S. BANCORP ADVISORS, LLC' },
	{ crd: '79', type: 'firm', label: 'J.P. MORGAN SECURITIES LLC' },
	{ crd: '1024851', type: 'individual', label: 'Christopher W Berkland' },
	{ crd: '1347157', type: 'individual', label: 'R ANTHONY CIOFFARI' },
	{ crd: '149777', type: 'firm', label: 'MORGAN STANLEY' },
	{ crd: '1414691', type: 'individual', label: 'STEPHEN MICHAEL YOUHN' },
	{ crd: '17490', type: 'firm', label: 'NATCITY INVESTMENTS, INC.' },
	{ crd: '169823', type: 'firm', label: 'SUMMIT GROUP RETIREMENT PLANNERS, INC.' },
	{ crd: '5059176', type: 'individual', label: 'Patricia Rutherford Mccallop' },
	{ crd: '1227500', type: 'individual', label: 'MALINDA NADENE WILLIAMS' },
	{ crd: '1126819', type: 'individual', label: 'KENNETH ANTHONY MADSEN' },
	{ crd: '1434842', type: 'individual', label: 'WARD RUSSELL BRICKNER' },
	{ crd: '10299', type: 'firm', label: 'CETERA ADVISORS LLC' },
	{ crd: '13572', type: 'firm', label: 'CETERA WEALTH SERVICES, LLC' },
	{ crd: '1090777', type: 'individual', label: 'David Darrel Brown' },
	{ crd: '35490', type: 'firm', label: 'INVESTMENT DISTRIBUTORS, INC.' },
	{ crd: '15340', type: 'firm', label: 'CETERA INVESTMENT SERVICES LLC' },
	{ crd: '105644', type: 'firm', label: 'CETERA INVESTMENT ADVISERS LLC' },
	{ crd: '15708', type: 'firm', label: 'PROEQUITIES, INC.' },
	{ crd: '4392432', type: 'individual', label: 'Remmy B Aguilar' },
	{ crd: '1028884', type: 'individual', label: 'ANDREW ROSS EPSTEIN' },
	{ crd: '111147', type: 'firm', label: 'EP WEALTH ADVISORS' },
	{ crd: '5393', type: 'firm', label: 'CHARLES SCHWAB & CO., INC.' },
	{ crd: '505', type: 'firm', label: 'LADENBURG THALMANN & CO. INC.' },
	{ crd: '6385308', type: 'individual', label: 'Andrew Wayne Hanna' },
	{ crd: '133763', type: 'firm', label: 'SAGEPOINT FINANCIAL, INC.' },
	{ crd: '1037871', type: 'individual', label: 'PHILLIP HOWARD PALMER' },
	{ crd: '2176816', type: 'individual', label: 'Erinn June Ford' },
	{ crd: '1751557', type: 'individual', label: 'NOEL DAVID BENNETT' },
	{ crd: '1104206', type: 'individual', label: 'Neil David Hackman' },
	{ crd: '1378651', type: 'individual', label: 'DALE ROBERT ANDERSON' },
	{ crd: '1149077', type: 'individual', label: 'ANTHONY JOHN FIORENZA' },
	{ crd: '1266773', type: 'individual', label: 'BARBARA LYNN MCMEEKIN' },
	{ crd: '1097277', type: 'individual', label: 'BRUCE GERALD BUSHMAN' },
	{ crd: '153319', type: 'firm', label: 'SAYBRUS EQUITY SERVICES, LLC' },
	{ crd: '1828345', type: 'individual', label: 'WALTER RUSSELL COSTENBADER' },
	{ crd: '1306464', type: 'individual', label: 'ROBERT PAUL GOTTSCHLING' },
	{ crd: '1056330', type: 'individual', label: 'LISA MARI SNYDERMAN' },
	{ crd: '2792129', type: 'individual', label: 'Michael B McNamee' },
	{ crd: '2119641', type: 'individual', label: 'Matthew John Mcnabb' },
	{ crd: '1010228', type: 'individual', label: 'Mark David Martino' },
	{ crd: '120222', type: 'firm', label: 'PRIVATE CLIENT SERVICES, LLC' },
	{ crd: '6413', type: 'firm', label: 'LPL FINANCIAL LLC' },
	{ crd: '340089', type: 'firm', label: 'VANDALIA WEALTH' },
	{ crd: '23131', type: 'firm', label: 'ROYAL ALLIANCE ASSOCIATES, INC.' },
	{ crd: '113681', type: 'individual', label: 'TOWNSEND' },
	{ crd: '1817181', type: 'individual', label: 'Jeffrey Wayne Brummet' },
	{ crd: '3157371', type: 'individual', label: 'Zachary David Trumpp' },
	{ crd: '793', type: 'firm', label: 'STIFEL, NICOLAUS & COMPANY, INCORPORATED' },
	{ crd: '1438619', type: 'individual', label: 'Rosmari Trump' },
	{ crd: '1085996', type: 'individual', label: 'Timothy Dale Register' },
	{ crd: '2637991', type: 'individual', label: 'Samuel D\'Arcy Cox Fox' },
	{ crd: '2602425', type: 'individual', label: 'Julie Thai' },
	{ crd: '6220', type: 'firm', label: 'HILLTOP SECURITIES INC.' },
	{ crd: '8109215', type: 'individual', label: 'Brook Tekle' },
	{ crd: '2606831', type: 'individual', label: 'David Myers Mink' },
	{ crd: '1087137', type: 'individual', label: 'Nina Bryan Nitti' },
	{ crd: '7556', type: 'firm', label: 'DEAN WITTER REYNOLDS INC.' },
	{ crd: '1090275', type: 'individual', label: 'H MICHAEL OKBY' },
	{ crd: '2292203', type: 'individual', label: 'Pamela Juni-Remy' },
	{ crd: '329291', type: 'firm', label: '360 ONE INC.' },
	{ crd: '147369', type: 'firm', label: 'CTL SECURITIES LLC' },
	{ crd: '132197', type: 'firm', label: 'AGM SECURITIES LLC' },
	{ crd: '155765', type: 'firm', label: 'BAYRIDGE SECURITIES, LLC' },
	{ crd: '154945', type: 'firm', label: 'DAM CAPITAL (USA) INC.' },
	{ crd: '2765376', type: 'individual', label: 'Anthony S. Hussain' },
	{ crd: '1160811', type: 'individual', label: 'Fredric Michael Obsbaum' },
	{ crd: '1839344', type: 'individual', label: 'Jay Spindel' },
	{ crd: '6141844', type: 'individual', label: 'Alan Spindel' },
	{ crd: '2268659', type: 'individual', label: 'Daniel Stuart Ibarra' },
	{ crd: '47107', type: 'firm', label: '' },
	{ crd: '284893', type: 'firm', label: 'SECURITIES CLUB BROKER-DEALER, LLC' },
	{ crd: '18272', type: 'firm', label: 'ALLSTATE FINANCIAL SERVICES, LLC' },
	{ crd: '285', type: 'firm', label: 'FERRIS, BAKER WATTS INCORPORATED' },
	{ crd: '5382457', type: 'individual', label: 'Jeffrey Eric Israel' },
	{ crd: '2144020', type: 'individual', label: 'KEITH H TRAN' },
	{ crd: '1819929', type: 'individual', label: 'David M Boccignone' },
	{ crd: '810432', type: 'individual', label: 'Wayne Ferman Hollingsworth' },
	{ crd: '8034610', type: 'individual', label: 'Steven Lundquist' },
	{ crd: '1247590', type: 'individual', label: 'James Charles Pazareskis' },
	{ crd: '4564408', type: 'individual', label: 'Paul T Keating' },
	{ crd: '7096395', type: 'individual', label: 'Devin Grayson' },
	{ crd: '1721973', type: 'individual', label: 'Douglas Lawrence Singer' },
	{ crd: '1277928', type: 'individual', label: 'TIMOTHY ALAN STALKER' },
	{ crd: '1870394', type: 'individual', label: 'Lori Cates Sarian' },
	{ crd: '2095368', type: 'individual', label: 'Timothy Patrick Ohara' },
	{ crd: '5449744', type: 'individual', label: 'CHRISTOPHER QUARTUCCIO' },
	{ crd: '4803269', type: 'individual', label: 'Fernando S Rivas' },
	{ crd: '2617191', type: 'individual', label: 'JILL FORD' },
	{ crd: '103767', type: 'firm', label: 'MARATHON CAPITAL MARKETS, LLC' },
	{ crd: '1046105', type: 'individual', label: 'Mark Elliot Paverman' },
	{ crd: '133146', type: 'firm', label: 'STILLPOINT CAPITAL, LLC' },
	{ crd: '299892', type: 'firm', label: 'IM GLOBAL US DISTRIBUTORS LLC' },
	{ crd: '128803', type: 'firm', label: 'OCM INVESTMENTS, LLC' },
	{ crd: '336681', type: 'firm', label: 'NOVELLUS SERVICES, LLC' },
	{ crd: '17140', type: 'firm', label: 'COMMERCE BROKERAGE SERVICES, INC.' },
	{ crd: '154217', type: 'firm', label: 'STONEPINE ADVISORS, LLC' },
	{ crd: '128801', type: 'firm', label: 'GENESIS CAPITAL, LLC' },
	{ crd: '315178', type: 'firm', label: 'MACARTHUR STRATEGIC CAPITAL, LLC' },
	{ crd: '6348245', type: 'individual', label: 'Anson Tsai' },
	{ crd: '145115', type: 'firm', label: 'MOELIS & COMPANY LLC' },
	{ crd: '1015047', type: 'individual', label: 'Kenneth David Moelis' },
	{ crd: '126292', type: 'firm', label: 'WELLS FARGO SECURITIES, LLC' },
	{ crd: '5455285', type: 'individual', label: 'DANIEL ANTONIO QUARANTA' },
	{ crd: '6504586', type: 'individual', label: 'Andrew Scott Munger' },
	{ crd: '1477620', type: 'individual', label: 'JONATHAN HUGH REGISTER' },
	{ crd: '2102288', type: 'individual', label: 'Steven Andrew Baronoff' },
	{ crd: '5374512', type: 'individual', label: 'Courtney Mckenzie Rogers Reid' },
	{ crd: '4034158', type: 'individual', label: 'Jason Craig Loveless' },
	{ crd: '4672504', type: 'individual', label: 'Laura P Chepucavage' },
	{ crd: '4213442', type: 'individual', label: 'Hadley Remy Joseph' },
	{ crd: '1237412', type: 'individual', label: 'JACK MARTIN ENOCH' },
	{ crd: '4194210', type: 'individual', label: 'Dale T Facey' },
	{ crd: '5529668', type: 'individual', label: 'VASILIOS J VARSAKOPOULOS' },
	{ crd: '5500659', type: 'individual', label: 'Daniel D Smith' },
	{ crd: '1040903', type: 'individual', label: 'ROSITA MASSIE' },
	{ crd: '15794', type: 'firm', label: 'BNP PARIBAS SECURITIES CORP.' },
	{ crd: '43629', type: 'firm', label: 'SAN FRANCISCO SECURITIES, INC.' },
	{ crd: '140203', type: 'firm', label: 'FUSEFI CAPITAL, LLC' },
	{ crd: '290765', type: 'firm', label: 'PCF CAPITAL MARKETS LLC' },
	{ crd: '1015679', type: 'firm', label: 'CARL VINCENT GOTTUSO' },
	{ crd: '146344', type: 'firm', label: 'INNOVATION PARTNERS LLC' },
	{ crd: '304566', type: 'firm', label: 'GLOBAL PACIFIC SECURITIES US, INC.' },
	{ crd: '26678', type: 'firm', label: 'BLEY INVESTMENT GROUP, INC.' },
	{ crd: '292310', type: 'firm', label: 'D-MERC SERVICES' },
	{ crd: '1577089', type: 'individual', label: 'James Pappas' },
	{ crd: '2022966', type: 'individual', label: 'Brett Alan Tekker' },
	{ crd: '1571445', type: 'individual', label: 'SARA GIBBS' },
	{ crd: '1170673', type: 'individual', label: 'PATRICK JOSEPH MARRON' },
	{ crd: '6894103', type: 'individual', label: 'Steven M. Mongelli' },
	{ crd: '7073312', type: 'individual', label: 'Thomas James Chiriaco' },
	{ crd: '2805008', type: 'individual', label: 'Pasquale S Pereez' },
	{ crd: '1179222', type: 'individual', label: 'PETER JAMES DESNOYERS' },
	{ crd: '2267743', type: 'individual', label: 'MICHAEL MCLAIN DALLAS' },
	{ crd: '1291732', type: 'individual', label: 'LOUIS RENSHAW FORTIER' },
	{ crd: '1206793', type: 'individual', label: 'Robert Townsend Edwards' },
	{ crd: '1404591', type: 'individual', label: 'June Marie Buzan' },
	{ crd: '824989', type: 'individual', label: 'James Townsend Tanner' },
	{ crd: '4925611', type: 'individual', label: 'Charles Jacob Lovelace' },
	{ crd: '2431627', type: 'individual', label: 'ALEX B SHORE' },
	{ crd: '858800', type: 'individual', label: 'David William Baugh' },
	{ crd: '8301', type: 'firm', label: 'E.V.I. GROUP LIMITED, INC.' },
	{ crd: '11025', type: 'firm', label: 'WELLS FARGO ADVISORS FINANCIAL NETWORK, LLC' },
	{ crd: '111221', type: 'firm', label: 'RSM MCGLADREY, INC.' },
	{ crd: '10740', type: 'firm', label: 'PROSPERA FINANCIAL SERVICES, INC.' },
	{ crd: '5979', type: 'firm', label: 'AMERIPRISE ADVISOR SERVICES, INC.' },
	{ crd: '16044', type: 'firm', label: 'HINSON EQUITY CORPORATION' },
	{ crd: '15840', type: 'firm', label: 'WALNUT STREET SECURITIES, INC.' },
	{ crd: '14733', type: 'firm', label: 'PLANNED MANAGEMENT COMPANY' },
	{ crd: '39550', type: 'firm', label: 'CITIZENS SECURITIES, INC.' },
	{ crd: '14549', type: 'firm', label: 'ALLIANCE FUND DISTRIBUTORS, INC.' },
	{ crd: '104555', type: 'firm', label: 'STRATEGIC ADVISERS LLC' },
	{ crd: '2726302', type: 'individual', label: 'Scott Hamilton Kurland' },
	{ crd: '42404', type: 'firm', label: 'SECOND STREET SECURITIES, INC.' },
	{ crd: '7186939', type: 'individual', label: 'ALI A. KHALIFA' },
	{ crd: '5478218', type: 'individual', label: 'Joseph Eugene Schmitt' },
	{ crd: '4373330', type: 'individual', label: 'Robert Samuel Coury' },
	{ crd: '6474129', type: 'individual', label: 'William David Adams' },
	{ crd: '297984', type: 'firm', label: 'IHT SECURITIES, LLC' },
	{ crd: '306063', type: 'firm', label: 'CMD GLOBAL PARTNERS, LLC' },
	{ crd: '2299633', type: 'individual', label: 'Thomas Edward Shea' },
	{ crd: '324243', type: 'firm', label: 'GCG SECURITIES, LLC' },
	{ crd: '207515', type: 'firm', label: 'SIGMA AMERICAS SECURITIES LLC' },
	{ crd: '307492', type: 'firm', label: 'NINTH ETERNITY SECURITIES LLC' },
	{ crd: '109211', type: 'firm', label: 'AMERICAN SKANDIA ADVISORY SERVICES, INC.' },
	{ crd: '42124', type: 'firm', label: 'ONE ORCHARD EQUITIES, INC.' },
	{ crd: '7133430', type: 'individual', label: 'Peter J Dracopoulos' },
	{ crd: '3202182', type: 'individual', label: 'Sara J Cavendish' },
	{ crd: '42324', type: 'firm', label: 'DOUGALL & ASSOCIATES INC.' },
	{ crd: '1039390', type: 'individual', label: 'C. David Hua Kim Wong' },
	{ crd: '4647659', type: 'individual', label: 'Sean Adam Worth' },
	{ crd: '242948', type: 'individual', label: 'Michael Allan Hendrickson' },
	{ crd: '47659', type: 'firm', label: 'STONEBRIDGE SECURITIES, LLC.' },
	{ crd: '5309', type: 'firm', label: 'FBL MARKETING SERVICES, LLC' },
	{ crd: '319208', type: 'firm', label: 'MORAN WEALTH MANAGEMENT, LLC' },
	{ crd: '7055089', type: 'individual', label: 'Stefanie Nmn Murray' },
	{ crd: '1855811', type: 'individual', label: 'Stanley John Lovelace' },
	{ crd: '105662', type: 'firm', label: 'ON INVESTMENT MANAGEMENT CO' },
	{ crd: '17507', type: 'firm', label: 'FIDELITY DISTRIBUTORS COMPANY LLC' },
	{ crd: '2936', type: 'firm', label: 'THE O.N. EQUITY SALES COMPANY' },
	{ crd: '28832', type: 'firm', label: 'JANUS HENDERSON DISTRIBUTORS US LLC' },
	{ crd: '5239489', type: 'individual', label: 'Nancy Alyce Lovelace' },
	{ crd: '2648626', type: 'individual', label: 'Theodus Mark Lovelace' },
	{ crd: '6405744', type: 'individual', label: 'Ryan Lovelace' },
	{ crd: '8348', type: 'firm', label: 'T. ROWE PRICE INVESTMENT SERVICES, INC.' },
	{ crd: '108958', type: 'firm', label: 'T. ROWE PRICE ADVISORY SERVICES, INC.' },
	{ crd: '8246217', type: 'individual', label: 'Jillian M Lovelace' },
	{ crd: '2275240', type: 'individual', label: 'S Diane Davis' },
	{ crd: '29251', type: 'firm', label: 'GREAT PACIFIC SECURITIES' },
	{ crd: '2853870', type: 'individual', label: 'JORDAN MARC CAHN' },
	{ crd: '106766', type: 'individual', label: 'ONEDIGITAL' },
	{ crd: '46605', type: 'firm', label: 'ESSEX SECURITIES LLC' },
	{ crd: '1751436', type: 'individual', label: 'THOMAS HEATH PARKER' },
	{ crd: '833', type: 'firm', label: 'TOWER SQUARE SECURITIES, INC.' },
	{ crd: '1685505', type: 'individual', label: 'JAMES KEVIN NOBLE' },
	{ crd: '1290702', type: 'individual', label: 'THEODORE BRET THIEL' },
	{ crd: '4095', type: 'firm', label: 'METROPOLITAN LIFE INSURANCE COMPANY' },
	{ crd: '14251', type: 'firm', label: 'METLIFE SECURITIES INC.' },
	{ crd: '4297', type: 'firm', label: 'NOMURA SECURITIES INTERNATIONAL, INC.' },
	{ crd: '4654545', type: 'individual', label: 'Ann Macdonald Junius' },
	{ crd: '2036762', type: 'individual', label: 'PAMELA ELAINE PROHONIC' },
	{ crd: '6375494', type: 'individual', label: 'China Claire Wilson' },
	{ crd: '5808776', type: 'individual', label: 'DANIEL JOHN QUARTUCIO' },
	{ crd: '306275', type: 'firm', label: 'RUNNING POINT CAPITAL ADVISORS LLC' },
	{ crd: '147573', type: 'firm', label: 'KENNEDY WEALTH MANAGEMENT, LLC' },
	{ crd: '286338', type: 'firm', label: 'O\'KEEFE STEVENS ADVISORY, INC.' },
	{ crd: '322250', type: 'firm', label: 'PRIMERICA BROKERAGE SERVICES, INC.' },
	{ crd: '705', type: 'firm', label: 'RAYMOND JAMES & ASSOCIATES, INC.' },
	{ crd: '1810059', type: 'individual', label: 'CLARENCE DALE SMITH' },
	{ crd: '1921998', type: 'individual', label: 'GUY MURRAY' },
	{ crd: '2223412', type: 'individual', label: 'PATRICK RODGERS BROOKS' },
	{ crd: '285387', type: 'firm', label: 'HONEY BADGER INVESTMENT SECURITIES, LLC' },
	{ crd: '172455', type: 'firm', label: 'NUVAMA FINANCIAL SERVICES INC.' },
	{ crd: '336257', type: 'firm', label: 'XORRO LLC' },
	{ crd: '337272', type: 'firm', label: 'GLOBAL81 US LLC' },
	{ crd: '316331', type: 'firm', label: 'BOFA SECURITIES PRIME, INC.' },
	{ crd: '5290525', type: 'individual', label: 'Vincent C. Santanna' },
	{ crd: '4204052', type: 'individual', label: 'Matthew C Mcqueen' },
	{ crd: '2522409', type: 'individual', label: 'Sarang Rajan Gadkari' },
	{ crd: '2597167', type: 'individual', label: 'Jennifer C Stagg' },
	{ crd: '6300829', type: 'individual', label: 'Glen Alexander Rae' },
	{ crd: '6238033', type: 'individual', label: 'Julien Louis Remi Climent' },
	{ crd: '6125084', type: 'individual', label: 'Phuong Thai' },
	{ crd: '2591231', type: 'individual', label: 'Jack W Parker' },
	{ crd: '1345942', type: 'individual', label: 'FRAN PRINCE' },
	{ crd: '4862136', type: 'individual', label: 'Phillip Mark Grandison' },
	{ crd: '1306242', type: 'individual', label: 'TONYA L LANKFORD' },
	{ crd: '2239528', type: 'individual', label: 'PATRICIA REED CENTENO' },
	{ crd: '4205783', type: 'individual', label: 'Jacqueline Michelle Cavendish' },
	{ crd: '1029421', type: 'individual', label: 'Michael Dean Cavendish' },
	{ crd: '110916', type: 'firm', label: 'MARSHFIELD ASSOCIATES' },
	{ crd: '164081', type: 'firm', label: 'AXXCESS WEALTH MANAGEMENT, LLC' },
	{ crd: '146415', type: 'firm', label: 'PLEIN AIR CAPITAL ADVISERS, LLC' },
	{ crd: '4660266', type: 'individual', label: 'ANGELA DIANE LUCAS' },
	{ crd: '104435', type: 'firm', label: 'GENEVA STOCK, L.L.C.' },
	{ crd: '250', type: 'firm', label: 'EDWARD JONES' },
	{ crd: '1007124', type: 'individual', label: 'Carla Lang' },
	{ crd: '151559', type: 'firm', label: 'CERITY PARTNERS LLC' },
	{ crd: '106293', type: 'firm', label: 'OAK FINANCIAL GROUP INC' },
	{ crd: '10111', type: 'firm', label: 'PFS INVESTMENTS INC.' },
	{ crd: '35350', type: 'firm', label: 'NYLIFE DISTRIBUTORS LLC' },
	{ crd: '110826', type: 'firm', label: 'EAGLE STRATEGIES LLC' },
	{ crd: '5167', type: 'firm', label: 'NYLIFE SECURITIES LLC' },
	{ crd: '26091', type: 'firm', label: 'BANC OF AMERICA SECURITIES LLC' },
	{ crd: '10409', type: 'firm', label: 'MML INVESTORS SERVICES, LLC' },
	{ crd: '153585', type: 'firm', label: 'SIMPLEX TRADING, LLC' },
	{ crd: '38455', type: 'firm', label: 'MATRIX EXECUTIONS, LLC' },
	{ crd: '311274', type: 'firm', label: 'AQUAS FINANCIAL, LLC' },
	{ crd: '1684119', type: 'individual', label: 'WILLIAM AUGUST CHOLAWA' },
	{ crd: '22982', type: 'firm', label: 'THE BENCHMARK COMPANY, LLC' },
	{ crd: '31194', type: 'firm', label: 'RBC CAPITAL MARKETS, LLC' },
	{ crd: '199', type: 'firm', label: 'D.A. DAVIDSON & CO.' },
	{ crd: '8174', type: 'firm', label: 'UBS FINANCIAL SERVICES INC.' },
	{ crd: '19616', type: 'firm', label: 'WELLS FARGO CLEARING SERVICES, LLC' },
	{ crd: '1102675', type: 'individual', label: 'Robert David O\'Brien' },
	{ crd: '1010582', type: 'individual', label: 'JOSEPH ARTHUR COLLERAN' },
	{ crd: '47957', type: 'firm', label: 'BRUDERMAN BROTHERS LLC' },
	{ crd: '327903', type: 'firm', label: 'IFAST SECURITIES US CORPORATION' },
	{ crd: '305928', type: 'firm', label: 'ALBERT SECURITIES, LLC' },
	{ crd: '324105', type: 'firm', label: 'NOMAD INVESTMENT SERVICES' },
	{ crd: '46929', type: 'firm', label: 'REGIONAL INVESTMENT SERVICES, INC.' },
	{ crd: '42180', type: 'firm', label: 'SUNBELT SECURITIES, INC.' },
	{ crd: '17587', type: 'firm', label: 'MOMENTUM INDEPENDENT NETWORK INC.' },
	{ crd: '1030727', type: 'individual', label: 'David King Medanich' },
	{ crd: '1004169', type: 'individual', label: 'David Edgar' },
	{ crd: '2646681', type: 'individual', label: 'Alan R Carlisle' },
	{ crd: '166243', type: 'firm', label: 'CHESTNUT FINANCIAL ADVISERS, INC.' },
	{ crd: '281539', type: 'firm', label: 'NOBLES & RICHARDS ADVISORS, LLC' },
	{ crd: '2704881', type: 'individual', label: 'ILONKA NOBLES' },
	{ crd: '17606', type: 'firm', label: 'MILKIE/FERGUSON INVESTMENTS, INC.' },
	{ crd: '31951', type: 'firm', label: 'REEF SECURITIES, INC.' },
	{ crd: '146870', type: 'firm', label: 'NOBLES & RICHARDS, INC.' },
	{ crd: '103800', type: 'firm', label: 'BV SECURITIES, LLC' },
	{ crd: '145', type: 'firm', label: 'LINCOLN FINANCIAL DISTRIBUTORS, INC.' },
	{ crd: '42046', type: 'firm', label: 'NFP ADVISOR SERVICES, LLC' },
	{ crd: '111436', type: 'firm', label: 'LEGACY CAPITAL GROUP CALIFORNIA, INC.' },
	{ crd: '139627', type: 'firm', label: 'INTEGRITY ALLIANCE, LLC.' },
	{ crd: '150801', type: 'firm', label: 'REACT INVESTMENT SOLUTIONS, LLC' },
	{ crd: '165828', type: 'firm', label: 'LION STREET FINANCIAL, LLC' },
	{ crd: '281242', type: 'firm', label: 'M1 FINANCE LLC' },
	{ crd: '316641', type: 'firm', label: 'FREC SECURITIES LLC' },
	{ crd: '103787', type: 'firm', label: 'TRADEWEB DIRECT LLC' },
	{ crd: '25910', type: 'firm', label: 'NATIONWIDE FUND DISTRIBUTORS LLC' },
	{ crd: '249787', type: 'individual', label: 'M1 FINANCE' },
	{ crd: '325982', type: 'individual', label: 'FREC' },
	{ crd: '2177490', type: 'individual', label: 'William John Baugh' },
	{ crd: '1761176', type: 'individual', label: 'Angelo O Ojeda' },
	{ crd: '1021195', type: 'individual', label: 'Peter Shaw O\'Keefe' },
	{ crd: '6801475', type: 'individual', label: 'Jake H. Karp' },
	{ crd: '7007608', type: 'individual', label: 'Jesse Howard Israel' },
	{ crd: '2276823', type: 'individual', label: 'Gregg Andrew Okeefe' },
	{ crd: '3014225', type: 'individual', label: 'EUGENE DONALD HEFLIN' },
	{ crd: '311317', type: 'firm', label: 'THOMA BRAVO CAPITAL MARKETS, LLC' },
	{ crd: '26506', type: 'firm', label: 'AMERICAN ENTERPRISE INVESTMENT SERVICES INC.' },
	{ crd: '153184', type: 'firm', label: 'STRATOS WEALTH PARTNERS, LTD' },
	{ crd: '283330', type: 'firm', label: 'KESTRA ADVISORY SERVICES, LLC' },
	{ crd: '103973', type: 'firm', label: '' },
	{ crd: '126331', type: 'firm', label: 'OLYMPIA ASSET MANAGEMENT,LTD.' },
	{ crd: '1101', type: 'firm', label: 'NATIXIS SECURITIES AMERICAS LLC' },
	{ crd: '6147479', type: 'individual', label: 'SARAH LUJAN' },
	{ crd: '4808341', type: 'individual', label: 'Edward Karl Duch III' },
	{ crd: '7323924', type: 'individual', label: 'Dominic Blue' },
	{ crd: '5026710', type: 'individual', label: 'Douglas Robert Steele' },
	{ crd: '1444771', type: 'individual', label: 'Geoffrey Craddock' },
	{ crd: '3169759', type: 'individual', label: 'GABRIEL STEVEN BORTHWICK' },
	{ crd: '3229894', type: 'individual', label: 'Matthew T Digangi' },
	{ crd: '5290483', type: 'individual', label: 'James Puhala' },
	{ crd: '2899239', type: 'individual', label: 'JAMES DAVID NIKOLAI' },
	{ crd: '1587368', type: 'individual', label: 'Dominick Iorio' },
	{ crd: '38030', type: 'firm', label: 'MML DISTRIBUTORS, LLC' },
	{ crd: '168638', type: 'firm', label: 'MML STRATEGIC DISTRIBUTORS, LLC' },
	{ crd: '3145101', type: 'individual', label: 'YEN ANH NGUYEN' },
	{ crd: '13042', type: 'firm', label: 'UBS FINANCIAL SERVICES INCORPORATED OF PUERTO RICO' },
	{ crd: '30833', type: 'firm', label: 'CENTAURUS FINANCIAL, INC.' },
	{ crd: '17499', type: 'firm', label: 'TRUIST INVESTMENT SERVICES, INC.' },
	{ crd: '4186475', type: 'individual', label: 'RICHARD LEE MCADAMS' },
	{ crd: '6845686', type: 'individual', label: 'James William Baugh' },
	{ crd: '283390', type: 'firm', label: 'TRUIST ADVISORY SERVICES, INC.' },
	{ crd: '6795558', type: 'individual', label: 'Kristin M.m. Gaston' },
	{ crd: '1302159', type: 'individual', label: 'Morihiko Goto' },
	{ crd: '7383813', type: 'individual', label: 'Remy James Fletcher' },
	{ crd: '5348108', type: 'individual', label: 'John William Holmes' },
	{ crd: '2402752', type: 'individual', label: 'JAY JOSEPH LASALLE' },
	{ crd: '2859774', type: 'individual', label: 'Venita June Renyer-Marke' },
	{ crd: '4719802', type: 'individual', label: 'Mitchell Lloyd Trellis' },
	{ crd: '1943140', type: 'individual', label: 'Walter Mathew Bokovitz' },
	{ crd: '8137832', type: 'individual', label: 'Jeremi C. Holmes' },
	{ crd: '2573543', type: 'individual', label: 'Michael Haskel Nessim' },
	{ crd: '5319490', type: 'individual', label: 'Mohamed A Alsoraimi' },
	{ crd: '154604', type: 'firm', label: 'FUTUREADVISOR, INC.' },
	{ crd: '5791518', type: 'individual', label: 'Adrian Nmn Exposito' },
	{ crd: '3259800', type: 'individual', label: 'JOSEPH STUART MONESTERE' },
	{ crd: '4213702', type: 'individual', label: 'EFTHALIA PALANTZAS KOTSIS' },
	{ crd: '1317929', type: 'individual', label: 'JENNIFER KERBY ARACRI' },
	{ crd: '5693810', type: 'individual', label: 'Stephen Ryan Fischer' },
	{ crd: '105146', type: 'firm', label: 'SEI INVESTMENTS MANAGEMENT CORP' },
	{ crd: '2106767', type: 'individual', label: 'DAVID HOWARD SHORE' },
	{ crd: '13071', type: 'firm', label: 'U.S. CLEARING CORP.' },
	{ crd: '1296293', type: 'individual', label: 'Michael Merritt Talbot' },
	{ crd: '127236', type: 'firm', label: 'NORTH FORK FINANCIAL ADVISORS LLC' },
	{ crd: '106237', type: 'firm', label: 'AVANTAX PLANNING PARTNERS, INC.' },
	{ crd: '127437', type: 'firm', label: 'COVINGTON ASSOCIATES, LLC' },
	{ crd: '1011480', type: 'individual', label: 'LEO OTTOWAY WHITLOW' },
	{ crd: '5767115', type: 'individual', label: 'Glen M Hackney' },
	{ crd: '2137293', type: 'individual', label: 'RYAN SCOTT VERNON' },
	{ crd: '2500963', type: 'individual', label: 'GABRIEL GARCIA' },
	{ crd: '3119188', type: 'individual', label: 'Jason Michael Mcghin' },
	{ crd: '4237394', type: 'individual', label: 'SHANTH DAVID' },
	{ crd: '2216151', type: 'individual', label: 'AARON MATTHEW PERSONS' },
	{ crd: '2737327', type: 'individual', label: 'JON HOWARD ROTHENBERG' },
	{ crd: '5299753', type: 'individual', label: 'Jennifer Hickman Campisi' },
	{ crd: '10690', type: 'firm', label: 'SEI INVESTMENTS DISTRIBUTION CO.' },
	{ crd: '103987', type: 'firm', label: 'LIQUIDNET, INC.' },
	{ crd: '2070306', type: 'individual', label: 'SEAN FARRELL' },
	{ crd: '10358', type: 'firm', label: 'CETERA FINANCIAL SPECIALISTS LLC' },
	{ crd: '332709', type: 'firm', label: 'CRESTWAVE CAPITAL PARTNERS LLC' },
	{ crd: '2207840', type: 'individual', label: 'MARCUS RAY HAMRICK' },
	{ crd: '111514', type: 'firm', label: 'AMERIVEST INVESTMENT MANAGEMENT, LLC' },
	{ crd: '325212', type: 'firm', label: 'C.R. LLOYD INVESTMENT SERVICES, LLC' },
	{ crd: '6790959', type: 'individual', label: 'DALLAS EARL KEYS' },
	{ crd: '5633', type: 'firm', label: 'TD AMERITRADE CLEARING, INC.' },
	{ crd: '7927528', type: 'individual', label: 'Jada Gilkerson' },
	{ crd: '1456415', type: 'individual', label: 'Sharon Jane Dyer' },
	{ crd: '7240122', type: 'individual', label: 'John Patrick Hamilton' },
	{ crd: '1476542', type: 'individual', label: 'GLENDA SUE BONE' },
	{ crd: '1339944', type: 'individual', label: 'MICKEY LEE HENDERSON' },
	{ crd: '2097046', type: 'individual', label: 'DAVID SUTTON MILLER' },
	{ crd: '1050957', type: 'individual', label: 'BRADLEY OWEN OLSON' },
	{ crd: '6344488', type: 'individual', label: 'ADAM BLAKE BONNER' },
	{ crd: '2446394', type: 'individual', label: 'BRANDON E. WEATHERFORD' },
	{ crd: '7717', type: 'firm', label: 'INDEPENDENT FINANCIAL GROUP, LLC' },
	{ crd: '4421942', type: 'individual', label: 'Ramey Thomas Harrell' },
	{ crd: '6383106', type: 'individual', label: 'Nichole Runions' },
	{ crd: '7728125', type: 'individual', label: 'Deepak Raj Thanigaivel' },
	{ crd: '1621000', type: 'individual', label: 'Timothy Vernon Bechtold' },
	{ crd: '7182907', type: 'individual', label: 'PRIYA MANIMARAN' },
	{ crd: '2959057', type: 'individual', label: 'James Daniel Lang' },
	{ crd: '18541', type: 'firm', label: 'OCC DISTRIBUTORS' },
	{ crd: '231', type: 'firm', label: 'THE DREYFUS SERVICE CORPORATION' },
	{ crd: '4207739', type: 'individual', label: 'PERPETRIAL TINESHA ANN COTTON' },
	{ crd: '6338029', type: 'individual', label: 'Chinie Fuhtrakoon' },
	{ crd: '2381858', type: 'individual', label: 'Timothy A Francis' },
	{ crd: '2744539', type: 'individual', label: 'Michelle Anne Barry' },
	{ crd: '4667709', type: 'individual', label: 'Nathaniel Tjoa' },
	{ crd: '142638', type: 'firm', label: 'DYNAMIC TRADING MANAGEMENT, LLC.' },
	{ crd: '5929176', type: 'individual', label: 'Zachary Henry Zelman' },
	{ crd: '1121184', type: 'individual', label: 'Laura Lee Hanson Virginia' },
	{ crd: '5895849', type: 'individual', label: 'Oleg A. Zaytsev' },
	{ crd: '6135652', type: 'individual', label: 'Michael Liverano' },
	{ crd: '153777', type: 'firm', label: 'CITI PRIVATE ALTERNATIVES, LLC' },
	{ crd: '2914374', type: 'individual', label: 'MICHAEL DAVID REMAK' },
	{ crd: '5290948', type: 'individual', label: 'ZOHAIB TARIQ' },
	{ crd: '4761025', type: 'firm', label: 'NOEL MICHAEL O\'REILLY' },
	{ crd: '2760137', type: 'individual', label: 'JOHN CONSTANTINE PROCOPION' },
	{ crd: '146991', type: 'firm', label: 'OLD MISSION CAPITAL, LLC' },
	{ crd: '5404464', type: 'individual', label: 'Sherianne N Gaskalla' },
	{ crd: '7059', type: 'firm', label: 'CITIGROUP GLOBAL MARKETS INC.' },
	{ crd: '47263', type: 'firm', label: 'REID & RUDIGER LLC' },
	{ crd: '4778972', type: 'individual', label: 'JAREL THOMAS CARROLL' },
	{ crd: '5975662', type: 'individual', label: 'THOMAS EDWARD CARROLL' },
	{ crd: '7786078', type: 'individual', label: 'James Leland Highland' },
	{ crd: '2756066', type: 'individual', label: 'Michael Owen Bunsis' },
	{ crd: '174129', type: 'firm', label: 'KNIGHTS OF COLUMBUS ASSET ADVISORS LLC' },
	{ crd: '18476', type: 'firm', label: 'TD SECURITIES (USA) LLC' },
	{ crd: '2648637', type: 'individual', label: 'JEFFREY SARGENT' },
	{ crd: '1938224', type: 'individual', label: 'THOMAS PETER GILLIS' },
	{ crd: '2554945', type: 'individual', label: 'TIMOTHY DELANEY' },
	{ crd: '288898', type: 'firm', label: 'KINGSWOOD CAPITAL PARTNERS, LLC' },
	{ crd: '288792', type: 'firm', label: 'KINGSWOOD WEALTH ADVISORS, LLC' },
	{ crd: '6829087', type: 'individual', label: 'Eileen Kelley' },
	{ crd: '8017463', type: 'individual', label: 'Sadie Lynne Keating' },
	{ crd: '5482642', type: 'individual', label: 'Maximilian Smith Caldwell' },
	{ crd: '2795963', type: 'individual', label: 'Avery H Kranz' },
	{ crd: '7003716', type: 'individual', label: 'Jamal D Eddie' },
	{ crd: '155071', type: 'firm', label: 'G.DISTRIBUTORS, LLC' },
	{ crd: '6100774', type: 'individual', label: 'Shumpei Oishi' },
	{ crd: '4366435', type: 'individual', label: 'Bjorn Jordan' },
	{ crd: '2112300', type: 'individual', label: 'TIMOTHY P BRADLEY' },
	{ crd: '6109762', type: 'individual', label: 'ADAM CHRISTIAN BONNER' },
	{ crd: '1391627', type: 'individual', label: 'Russell Paul Green' },
	{ crd: '1098844', type: 'individual', label: 'R Gregg Nabhan' },
	{ crd: '4622993', type: 'individual', label: 'Ashley Grissom' },
	{ crd: '1950281', type: 'individual', label: 'Linda Dianne Parma' },
	{ crd: '7560', type: 'firm', label: 'DONALDSON, LUFKIN & JENRETTE SECURITIES CORPORATION' },
	{ crd: '104395', type: 'firm', label: 'ENSPIRE INVESTMENTS' },
	{ crd: '4895304', type: 'individual', label: 'James J Deats' },
	{ crd: '2683746', type: 'individual', label: 'JAMES CHRISTOPHER FREEMAN' },
	{ crd: '1417511', type: 'individual', label: 'MATTHEW J PRICE' },
	{ crd: '6600103', type: 'individual', label: 'ALEXANDRIA FISHER' },
	{ crd: '4809405', type: 'individual', label: 'Philip J Cenatiempo' },
	{ crd: '5546717', type: 'individual', label: 'Gail Rachel Merken' },
	{ crd: '7861388', type: 'individual', label: 'Paula Von Israel' },
	{ crd: '299736', type: 'firm', label: 'FIDELITY PRIME FINANCING' },
	{ crd: '5392417', type: 'individual', label: 'Kevin Michael Mclaughlin' },
	{ crd: '4700374', type: 'individual', label: 'HANK BRIAN LOBEL' },
	{ crd: '7411334', type: 'individual', label: 'SAJIV CHANDRA' },
	{ crd: '166675', type: 'firm', label: '303 ALTERNATIVES, LLC' },
	{ crd: '329378', type: 'firm', label: 'PARX TRADING, LLC' },
	{ crd: '7097197', type: 'individual', label: 'Leandro Jesus Goicoechea' },
	{ crd: '6106132', type: 'individual', label: 'Bradford R Arlington' },
	{ crd: '7411657', type: 'individual', label: 'Remko B.h. Huibers' },
	{ crd: '310544', type: 'firm', label: 'MAVERICK DERIVATIVES' },
	{ crd: '5695967', type: 'individual', label: 'Timothy Kirk Israel' },
	{ crd: '309996', type: 'firm', label: 'JOSEPH WEALTH MANAGEMENT, LLC' },
	{ crd: '277027', type: 'firm', label: 'TASTYTRADE, INC.' },
	{ crd: '337482', type: 'firm', label: 'MA SECURITIES LLC' },
	{ crd: '327863', type: 'firm', label: 'TTBD, LLC' },
	{ crd: '309241', type: 'firm', label: 'BLACK EDGE SECURITIES LLC' },
	{ crd: '322438', type: 'firm', label: 'STG SECURITIES, LLC' },
	{ crd: '147763', type: 'firm', label: 'AVATAR SECURITIES, LLC' },
	{ crd: '4946514', type: 'individual', label: 'STEVEN D JUNO' },
	{ crd: '2318839', type: 'individual', label: 'NORRIS GATES COTTON' },
	{ crd: '4422849', type: 'individual', label: 'Craig Evan Bauer' },
	{ crd: '326690', type: 'firm', label: 'ERUDITE TRADING LLC' },
	{ crd: '114061', type: 'firm', label: 'JAG TRADING L.L.C.' },
	{ crd: '2595217', type: 'individual', label: 'George Orson Papa' },
	{ crd: '146310', type: 'firm', label: 'SUMO CAPITAL, LLC' },
	{ crd: '148743', type: 'firm', label: 'SPIDERROCK EXS, LLC' },
	{ crd: '170803', type: 'firm', label: 'LEAGUE CAPITAL MARKETS' },
	{ crd: '16164', type: 'firm', label: 'TRANSAMERICA FINANCIAL ADVISORS, INC' },
	{ crd: '39543', type: 'firm', label: 'CAMBRIDGE INVESTMENT RESEARCH, INC.' },
	{ crd: '134139', type: 'firm', label: 'CAMBRIDGE INVESTMENT RESEARCH ADVISORS, INC.' },
	{ crd: '286262', type: 'firm', label: 'INDEPENDENT WEALTH NETWORK, INC.' },
	{ crd: '35371', type: 'firm', label: 'OSAIC INSTITUTIONS, INC.' },
	{ crd: '7784', type: 'firm', label: 'FIDELITY BROKERAGE SERVICES LLC' },
	{ crd: '2496177', type: 'individual', label: 'Kiriakos Andreas Evangeliou' },
	{ crd: '6989441', type: 'individual', label: 'Israel Rojkind Ramos' },
	{ crd: '2860344', type: 'individual', label: 'June Denise Herrell' },
	{ crd: '1145401', type: 'individual', label: 'EDWARD GEORGE MARTELL' },
	{ crd: '1502351', type: 'individual', label: 'JAMES ALTON KELLEY' },
	{ crd: '5957015', type: 'individual', label: 'Israel Olman Martinez Magana' },
	{ crd: '1497238', type: 'individual', label: 'THOMAS JOSEPH TOPPER' },
	{ crd: '2842125', type: 'individual', label: 'David Leland Darlington' },
	{ crd: '1244572', type: 'individual', label: 'Lawrence Anton Thiel' },
	{ crd: '6471011', type: 'individual', label: 'Stephane Joseph Israel' },
	{ crd: '1985568', type: 'individual', label: 'Carlos Verner Ubinas Taylor' },
	{ crd: '1946333', type: 'individual', label: 'William George Pendleton' },
	{ crd: '5097259', type: 'individual', label: 'KIRBY LEPAK HORAN-ADAMS' },
	{ crd: '1192888', type: 'individual', label: 'John P Holmes' },
	{ crd: '2492045', type: 'individual', label: 'David Allegra' },
	{ crd: '4733816', type: 'individual', label: 'Bridget Cary Baugh' },
	{ crd: '2005235', type: 'individual', label: 'A Charles Krempa' },
	{ crd: '1584057', type: 'individual', label: 'MICHAEL PATRICK HENDERSON' },
	{ crd: '1502437', type: 'individual', label: 'JOSEPH CHARLES MCGEE' },
	{ crd: '288886', type: 'firm', label: 'SMITH SECURITIES LLC' },
	{ crd: '2689484', type: 'individual', label: 'JOSHUA MICHAEL HOWELL' },
	{ crd: '2602468', type: 'individual', label: 'David Israel' },
	{ crd: '3198065', type: 'individual', label: 'Israel Wilfredo Torres' },
	{ crd: '147363', type: 'firm', label: 'MERCER GLOBAL ADVISORS INC.' },
	{ crd: '7021400', type: 'individual', label: 'Israel Cruz Gonzalez' },
	{ crd: '6780385', type: 'individual', label: 'Israel David Bentley' },
	{ crd: '7163738', type: 'individual', label: 'Avner Israel' },
	{ crd: '106715', type: 'firm', label: 'VANGUARD ADVISERS, INC.' },
	{ crd: '42057', type: 'firm', label: 'ARVEST WEALTH MANAGEMENT' },
	{ crd: '5040823', type: 'individual', label: 'Jeremy Ross Intihar' },
	{ crd: '151317', type: 'firm', label: 'ISRAELS FERGUSON ASSET ADVISORS LLC' },
	{ crd: '2015122', type: 'individual', label: 'Michael Jozef Israels' },
	{ crd: '106015', type: 'firm', label: 'TRUSTMONT ADVISORY GROUP, INC.' },
	{ crd: '5623080', type: 'individual', label: 'Mary Lynne Hixenbaugh' },
	{ crd: '3085120', type: 'individual', label: 'Melissa Jean Sparks' },
	{ crd: '7938039', type: 'individual', label: 'Mashah B Israel' },
	{ crd: '2757521', type: 'individual', label: 'Richard Raymond Israel' },
	{ crd: '298137', type: 'firm', label: 'ACCURATE WEALTH MANAGEMENT, LLC' },
	{ crd: '11643', type: 'firm', label: 'HORACE MANN INVESTORS INC' },
	{ crd: '1676130', type: 'individual', label: 'Raymond Thomas Spinelli' },
	{ crd: '5761394', type: 'individual', label: 'Farah Eden Israel' },
	{ crd: '6357636', type: 'individual', label: 'David Michael Israel' },
	{ crd: '8209', type: 'firm', label: 'MORGAN STANLEY & CO. LLC' },
	{ crd: '128351', type: 'firm', label: 'SG AMERICAS SECURITIES, LLC' },
	{ crd: '4616863', type: 'individual', label: 'Michael Scott Israel' },
	{ crd: '286643', type: 'firm', label: 'REVOLVE WEALTH PARTNERS, LLC' },
	{ crd: '1439611', type: 'individual', label: 'DAVID GERARD LUTSCH' },
	{ crd: '2021508', type: 'individual', label: 'W KENT EARLY' },
	{ crd: '5181', type: 'firm', label: 'JOHN HANCOCK MUTUAL LIFE INSURANCE COMPANY' },
	{ crd: '7381661', type: 'individual', label: 'Winnie Lee' },
	{ crd: '4498537', type: 'individual', label: 'George Andrew Gill' },
	{ crd: '2080220', type: 'individual', label: 'GREGORY EMMANUEL RICCA' },
	{ crd: '1250491', type: 'individual', label: 'THOMAS JUDE SEMMES HUGHS' },
	{ crd: '1742347', type: 'individual', label: 'MICHAEL BENJAMIN DAVIS' },
	{ crd: '285300', type: 'firm', label: 'BRIGHTHOUSE SECURITIES, LLC' },
	{ crd: '12428', type: 'individual', label: 'ALAN BARHAM' },
	{ crd: '1034884', type: 'individual', label: 'ALTON L YOUNG' },
	{ crd: '109524', type: 'firm', label: 'ALLSTATE FINANCIAL ADVISORS, LLC' },
	{ crd: '5888281', type: 'individual', label: 'NICHOLAS THOMAS CONSTANTINO' },
	{ crd: '1401203', type: 'individual', label: 'Ricky Black' },
	{ crd: '847129', type: 'individual', label: 'MICHAEL SALVATORE CONSTANTINO' },
	{ crd: '6377990', type: 'individual', label: 'DAVID JOSEPH CONSTANTINO' },
	{ crd: '519', type: 'firm', label: 'LINCOLN INVESTMENT' },
	{ crd: '2978681', type: 'individual', label: 'Scott Sullivan Delaney' },
	{ crd: '2799083', type: 'individual', label: 'MICHAEL JOSEPH SHEA' },
	{ crd: '1137', type: 'firm', label: 'PRINCOR FINANCIAL SERVICES CORPORATION' },
	{ crd: '468', type: 'firm', label: 'JOHN HANCOCK DISTRIBUTORS, INC.' },
	{ crd: '1972370', type: 'individual', label: 'Patrick John Brown' },
	{ crd: '282755', type: 'firm', label: 'ACCEPTUS CAPITAL CORP.' },
	{ crd: '3112184', type: 'individual', label: 'John Baugh' },
	{ crd: '15007', type: 'firm', label: 'AEGIS CAPITAL CORP.' },
	{ crd: '2278341', type: 'individual', label: 'JOSEPH MICHAEL GIORDANO' },
	{ crd: '3144471', type: 'individual', label: 'Adena June Cohen' },
	{ crd: '5346260', type: 'individual', label: 'Meredith Helsel Remme' },
	{ crd: '29275', type: 'firm', label: 'PTI SECURITIES & FUTURES L. P.' },
	{ crd: '2162854', type: 'individual', label: 'Daniel John Haugh' },
	{ crd: '148960', type: 'firm', label: 'TWO SIGMA SECURITIES, LLC' },
	{ crd: '3052310', type: 'individual', label: 'MARYJO RIDDLE' },
	{ crd: '2238449', type: 'individual', label: 'Craig Leishman Baugh' },
	{ crd: '6696223', type: 'individual', label: 'Spencer G Baugh' },
	{ crd: '29337', type: 'firm', label: 'SUSQUEHANNA CAPITAL GROUP' },
	{ crd: '134159', type: 'firm', label: 'JANE STREET OPTIONS, LLC' },
	{ crd: '167280', type: 'firm', label: 'JANE STREET EXECUTION SERVICES, LLC' },
	{ crd: '4406871', type: 'individual', label: 'Christina D Kramer' },
	{ crd: '3036', type: 'firm', label: 'PHOENIX EQUITY PLANNING CORPORATION' },
	{ crd: '164466', type: 'firm', label: 'NESTWISE LLC' },
	{ crd: '138164', type: 'firm', label: 'FORTIGENT, LLC' },
	{ crd: '32444', type: 'firm', label: 'FIRST ALLIED SECURITIES, INC.' },
	{ crd: '1664589', type: 'individual', label: 'DANNY DUFF PENNINGTON' },
	{ crd: '1200120', type: 'individual', label: 'S MARCUS HAWKINS' },
	{ crd: '1058874', type: 'individual', label: 'KENNETH ALAN MOUNT' },
	{ crd: '39011', type: 'firm', label: 'LEERINK SWANN & COMPANY' },
	{ crd: '8733', type: 'firm', label: 'LPL ENTERPRISE, LLC' },
	{ crd: '2510742', type: 'individual', label: 'Matthew Edwin Morningstar' },
	{ crd: '4168267', type: 'firm', label: 'ROBERT BRADLEY FINCHER' },
	{ crd: '1683225', type: 'individual', label: 'PETER GRENVILLE MAGNUSON' },
	{ crd: '4453784', type: 'individual', label: 'NOELLE GRANVILLE MCINTYRE' },
	{ crd: '134086', type: 'firm', label: 'LEVEL FOUR ADVISORY SERVICES' },
	{ crd: '168267', type: 'firm', label: 'INDEPENDENT ADVISOR ALLIANCE, LLC' },
	{ crd: '103782', type: 'firm', label: 'JANE STREET CAPITAL, LLC' },
	{ crd: '142106', type: 'firm', label: 'COLLABORATIVE WEALTH' },
	{ crd: '2170100', type: 'firm', label: 'SUSAN Z JENKINS' },
	{ crd: '167995', type: 'firm', label: 'GOLDEN STATE WEALTH MANAGEMENT, LLC' },
	{ crd: '1013304', type: 'individual', label: 'Raymond Mendez' },
	{ crd: '628', type: 'firm', label: 'FIFTH THIRD SECURITIES, INC.' },
	{ crd: '173447', type: 'firm', label: 'WARREN STREET WEALTH ADVISORS, LLC' },
	{ crd: '107726', type: 'firm', label: 'UBS INTERNATIONAL INC.' },
	{ crd: '151664', type: 'firm', label: 'BAYSTATE WEALTH MANAGEMENT' },
	{ crd: '615', type: 'firm', label: 'NEW ENGLAND SECURITIES' },
	{ crd: '43036', type: 'firm', label: 'STATE FARM VP MANAGEMENT CORP.' },
	{ crd: '20626', type: 'firm', label: 'WORLD INVESTMENTS, LLC' },
	{ crd: '19647', type: 'firm', label: 'MIZUHO SECURITIES USA LLC' },
	{ crd: '7421929', type: 'individual', label: 'Anya Baugh' },
	{ crd: '2790899', type: 'individual', label: 'Christopher Francis Winchenbaugh' },
	{ crd: '198516', type: 'firm', label: 'INTREPID PARTNERS, LLC' },
	{ crd: '130577', type: 'firm', label: 'MAITLAND SECURITIES, INC.' },
	{ crd: '127701', type: 'firm', label: 'GRADIENT SECURITIES, LLC' },
	{ crd: '18923', type: 'firm', label: 'TRANSAM SECURITIES, INC.' },
	{ crd: '42150', type: 'firm', label: 'FORTUNE FINANCIAL SERVICES, INC.' },
	{ crd: '1623293', type: 'individual', label: 'Remi Joseph Zecman' },
	{ crd: '18312', type: 'firm', label: 'TRUSTMONT FINANCIAL GROUP, INC.' },
	{ crd: '4257', type: 'firm', label: 'INVESTORS BROKERAGE SERVICES, INC.' },
	{ crd: '104510', type: 'firm', label: 'EDELMAN FINANCIAL ENGINES' },
	{ crd: '103863', type: 'firm', label: 'FARMERS FINANCIAL SOLUTIONS, LLC' },
	{ crd: '130847', type: 'firm', label: 'STANDARD CHARTERED SECURITIES NORTH AMERICA LLC' },
	{ crd: '19714', type: 'firm', label: 'BARCLAYS CAPITAL INC.' },
	{ crd: '7422254', type: 'individual', label: 'Remy Neuhaus' },
	{ crd: '166700', type: 'firm', label: 'WELLS STREET ADVISORS, LLC' },
	{ crd: '36848', type: 'firm', label: 'WOLVERINE TRADING, LLC' },
	{ crd: '2881', type: 'firm', label: 'NORTHWESTERN MUTUAL INVESTMENT SERVICES, LLC' },
	{ crd: '7233889', type: 'individual', label: 'Olivier Rodriguez Fachena' },
];

export const CHART_PRELOAD_CRDS: string[] = CHART_PRELOAD_SEEDS.map((s) => s.crd);
